language: node_js
node_js:
  - '9'
  - '10'
script:
  - npm i
  - lerna bootstrap
  - lerna run ci:test
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'npx codecov'
  - 'lerna publish --conventional-commits --canary=beta'