language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
  - node_modules
script:
  - npm i
  - lerna bootstrap --hoist
  - lerna run ci:test
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'npx codecov'
